[".zsh/powerlevel10k"]
    type = "git-repo"
    url = "git@github.com:romkatv/powerlevel10k.git"
    exact = true
    refreshPeriod = "168h"

[".zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "git@github.com:zsh-users/zsh-autosuggestions"
    exact = true
    refreshPeriod = "168h"

[".zsh/zsh-history-substring-search"]
    type = "git-repo"
    url = "git@github.com:zsh-users/zsh-history-substring-search"
    exact = true
    refreshPeriod = "168h"

[".zsh/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "git@github.com:zsh-users/zsh-syntax-highlighting.git"
    exact = true
    refreshPeriod = "168h"
[".tmux"]
    type = "git-repo"
    url = "git@github.com:gpakosz/.tmux.git"
    exact = true
    refreshPeriod = "168h"
[".zsh/forgit"]
    type = "git-repo"
    url = "git@github.com:wfxr/forgit.git"
    exact = true
    refreshPeriod = "168h"
