[".zsh/powerlevel10k"]
    type = "git-repo"
    url = "git@github-aon/romkatv/powerlevel10k.git"
    exact = true
    refreshPeriod = "168h"

[".zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "git@github-aon/zsh-users/zsh-autosuggestions"
    exact = true
    refreshPeriod = "168h"

[".zsh/zsh-history-substring-search"]
    type = "git-repo"
    url = "git@github-aon/zsh-users/zsh-history-substring-search"
    exact = true
    refreshPeriod = "168h"

[".zsh/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "git@github-aon/zsh-users/zsh-syntax-highlighting.git"
    exact = true
    refreshPeriod = "168h"

[".zsh/git-completion.bash"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    refreshPeriod = "168h"

[".zsh/git-completion.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh"
    refreshPeriod = "168h"

[".tmux"]
    type = "git-repo"
    url = "git@github-aon/gpakosz/.tmux.git"
    exact = true
    refreshPeriod = "168h"
